var config = {}
config.language = [
    {text:"Věcí"},
    {text:"Zbraní"},
    {text:"Uložiště"},
    {text:"Místo"},
    {text:"Správa oblečení"},
    {text:"Odložit nebo vzít klobouk"},
    {text:"Odložit nebo vzít brýle"},
    {text:"Odložit nebo vzít masku"},
    {text:"Odložit nebo vzít bandanu"},
    {text:"Odložit nebo vzít kravatu, šátek"},
    {text:"Odložit nebo vzít plášť, pončo"},
    {text:"Odložit nebo vzít košili"},
    {text:"Odložit nebo vzít vestu"},
    {text:"Odložit nebo vzít kabát"},
    {text:"Odložit nebo vzít muniční pásy, doplňky, brašny"},
    {text:"Odložit nebo vzít prsteny"},
    {text:"Odložit nebo vzít rukavice"},
    {text:"Odložit nebo vzít nátepníky"},
    {text:"Odložit nebo vzít pásek, přezku, pouzdra"},
    {text:"Odložit nebo vzít kšandy"},
    {text:"Odložit nebo vzít kalhoty, kamaše, chapsy"},
    {text:"Odložit nebo vzít boty"},
    {text:"Peníze"},
    {text:"Slouží jako platební měna."},
    {text:"Zlato"},
    {text:"Slouží jako platební měna."},
    {text:"Vybaveno"},
    {text:"Nevybaveno"},
    {text:"Zavřít"},//28
    {text:"Inventář"},
    {text:"Darovat"},
    {text:"Zahodit"},
]
