Config = {}

Config.Max_Items = 50
Config.Max_Weapons = 10

Config.Language = {
    [0] = {text = "Sebrat",},
    [1] = {text = "Zlato",},
    [2] = {text = "Peníze",},
    [3] = {text = "Potvrdit",},
    [4] = {text = "Kolik peněz chceš přesunout",},
    [5] = {text = "Kolik zlata chceš přesunout",},
    [6] = {text = "Kolik věcí chceš přesunout",},
    [7] = {text = "Nemůžeš vložit použitou zbraň",},
    [8] = {text = "Nemáš tam místo",},
    [10] = {text = "Inventář",},
    [11] = {text = "Nedržíš žádnou zbraň pro zobrazení",},
    [12] = {text = "Vybavil jsi první revolver.",},
    [13] = {text = "Vybavil jsi druhý revolver.",},
    [14] = {text = "Již máš vybavené dvě pistole.",},
    [15] = {text = "Vybavil jsi první hlavní zbraň.",},
    [16] = {text = "Vybavil jsi druhou hlavní zbraň.",},
    [17] = {text = "Již máš vybavené dvě hlavní zbraně.",},
    [18] = {text = "Vybavil jsi dodatkovou věc.",},
    [19] = {text = "Sundal jsi druhý revolver.",},
    [20] = {text = "Sundal jsi první revolver.",},
    [21] = {text = "Sundal jsi dodatkovou věc.",},
    [22] = {text = "Sundal jsi první zbraň.",},
    [23] = {text = "Sundal jsi druhou zbraň.",},
    [24] = {text = "Pytel s věcma",},
    [25] = {text = "Pytel se zlatem",},
    [26] = {text = "Hromádka peněz",},
    [27] = {text = "Bedna s ",},
    [28] = {text = "Podat ruku ",},
    [29] = {text = "Dát facku ",},
    [30] = {text = "Tolik toho nemáš.",},
    [31] = {text = "Neplatná hodnota.",},
    [32] = {text = "Nejdříve svou zbraň musíš odvybavit.",},
    [33] = {text = "Tolik u sebe nemáš.",},
    [34] = {text = "Nemáš u sebe tolik hotovosti.",},
    [35] = {text = "Nemáš u sebe tolik zlata.",},
    [36] = {text = "Nemůžeš zahodit vybavenou zbraň.",},
    [37] = {text = "Nemůžeš házet věci moc blízko.",},
    [38] = {text = "Toto uložiště není vytvořeno.",},
    [39] = {text = "Toto uložiště má již otevřeno někdo jiný.",},
    [40] = {text = "Nemáš tolik peněz.",},
    [41] = {text = "Nemáš místo v inventáři.",},
    [42] = {text = "Tolik toho neunese",},
    [43] = {text = "Neunese víc zbraní.",},
    [44] = {text = "Neuneseš víc zbraní.",},
}