Config = {}

Config.Max_Items = 50
Config.Max_Weapons = 10

Config.Language = {
    [0] = {text = "Prendre",},
    [1] = {text = "Or",},
    [2] = {text = "Dollars",},
    [3] = {text = "Confirmer",},
    [4] = {text = "Combien de dollars voulez-vous déplacer?",},
    [5] = {text = "Combien d'or voulez-vous déplacer?",},
    [6] = {text = "Combien d'objet voulez-vous déplacer",},
    [7] = {text = "Vous ne pouvez pas déposer une arme usagée",},
    [8] = {text = "Vous n'avez pas accès",},
    [10] = {text = "Inventaire",},
    [11] = {text = "Vous n'avez aucune arme à afficher",},
    [12] = {text = "Vous avez équipé le premier revolver.",},
    [13] = {text = "Vous avez équipé le deuxième revolver.",},
    [14] = {text = "Vous avez déjà deux revolver.",},
    [15] = {text = "Vous avez équipé la première arme principale.",},
    [16] = {text = "Vous avez équipé la deuxième arme principale.",},
    [17] = {text = "Vous avez déjà deux armes principales.",},
    [18] = {text = "Vous avez équipé un objet supplémentaire.",},
    [19] = {text = "Vous avez deséquipé votre deuxième revolver.",},
    [20] = {text = "Tu as sorti ton premier revolver.",},
    [21] = {text = "Vous avez deséquipé l'objet supplémentaire.",},
    [22] = {text = "Tu as enlevé ta première arme.",},
    [23] = {text = "Tu as enlevé ta deuxième arme.",},
    [24] = {text = "Sacoche",},
    [25] = {text = "Sac d'or",},
    [26] = {text = "Paquet de dollars",},
    [27] = {text = "lits",},
    [28] = {text = "Tendre la main ",},
    [29] = {text = "Gifler ",},
    [30] = {text = "Pas assez sur vous ! ",},
    [31] = {text = "valeur invalide.",},
    [32] = {text = "Vous devez d'abord équiper votre arme.",},
    [33] = {text = "Tu n'as pas grand chose sur toi.",},
    [34] = {text = "Vous n'avez pas beaucoup de dollars avec vous.",},
    [35] = {text = "Vous n'avez pas beaucoup d'or avec vous.",},
    [36] = {text = "Vous ne pouvez pas lâcher une arme équipée.",},
    [37] = {text = "Vous ne pouvez pas jeter les choses trop près l'une de l'autre.",},
    [38] = {text = "Ce dépôt n'est pas disponible.",},
    [39] = {text = "Quelqu'un d'autre possède déjà ce dépôt.",},
    [40] = {text = "Vous n'avez pas assez d'argent.",},
    [41] = {text = "Vous n'avez pas de place dans l'inventaire.",},
    [42] = {text = "Trop lourd !",},
    [43] = {text = "Vous avez trop d'armes sur vous !",},
    [44] = {text = "Vous ne pouvez pas porter plus d'armes.",},
}